DROP VIEW IF EXISTS v_kuntur.unc_in_enrrollment CASCADE;
CREATE OR REPLACE VIEW v_kuntur.unc_in_enrrollment AS 
	SELECT 
		unc_in_enrrollment.id /*id*/,
		unc_in_enrrollment.erased /*erased*/,
		unc_in_enrrollment.agreement /*Con Convenio*/,
		unc_in_enrrollment.program /*Con Programa*/,
		unc_in_enrrollment.amount_paid /*Tasa Pagada*/,
		unc_in_enrrollment.original_doc /*Documentación Original*/,
		unc_in_enrrollment.insurance /*Seguro*/,
		unc_in_enrrollment.language_certificate /*Certificado de Idioma*/,
		unc_in_enrrollment.visa /*Visa*/,
		unc_in_enrrollment.emergency_contact /*Contacto de Emergencia*/,
		unc_in_enrrollment.credential_code /*Código de Credencial*/,
		unc_in_enrrollment.url_origininal_transcript /*Analítico Académico*/,
		unc_in_enrrollment.url_passport /*Pasaporte*/,
		unc_in_enrrollment.url_language_certificate /*Certificado de Idioma*/,
		unc_in_enrrollment.url_cv /*Curriculumn Vitae*/,
		unc_in_enrrollment.url_application_letter /*Carta de Postulación*/,
		unc_in_enrrollment.url_certificate_psychophysical /*Certificado Psicofísico*/,
		unc_in_enrrollment.url_admission_act /*Acta de Admisión*/,
		unc_in_enrrollment.url_admission_act_template /*Template Acta de Admisión*/,
		unc_in_enrrollment.url_transcript /*Certificado Analítico*/,
		unc_in_enrrollment.url_transcript_template /*Template de Certificado Analítico*/,
		unc_in_enrrollment.url_university_credential /*Credencial Universitaria*/,
		unc_in_enrrollment.url_student_report /*Reporte del Estudiante*/,
		unc_in_enrrollment.url_exchange_form /*Formulario de Intercambio*/,
		unc_in_enrrollment.comment /*Comentario*/,
		unc_in_enrrollment.observation /*Observaciones*/,
		unc_in_enrrollment.creation_date_postulation /*Observaciones*/,
		unc_in_enrrollment.agreement_name /*Nombre del Acuerdo*/,
		unc_in_enrrollment.agreement_comment /*Comentario del Acuerdo*/,
		unc_in_enrrollment.agreement_number_students /*Cant. Estudiantes del Acuerdo*/,
		unc_in_enrrollment.agreement_org /*Institución del Acuerdo*/,
		unc_in_enrrollment.agreement_org_comment /*Comentario Institución del Acuerdo*/,
		unc_in_enrrollment.agreement_academic_unit /*Unidad Académica del Acuerdo*/,
		unc_in_enrrollment.exchange_program_name /*Nombre del Programa*/,
		unc_in_enrrollment.exchange_program_comment /*Comentario del Programa*/,
		unc_in_enrrollment.exchange_program_number_students /*Cant. Estudiantes del Programa*/,
		unc_in_enrrollment.exchange_program_initial_number_students /*Cant. Inicial Estudiantes del Programa*/,
		enrrollment.id AS enrrollment_id /*id*/,
		enrrollment.erased AS enrrollment_erased /*erased*/,
		enrrollment.given_name AS enrrollment_given_name /*Nombre de Pila*/,
		enrrollment.middle_name AS enrrollment_middle_name /*Segundo Nombre*/,
		enrrollment.family_name AS enrrollment_family_name /*Apellido*/,
		enrrollment.birth_date AS enrrollment_birth_date /*Fecha de Nacimiento*/,
		enrrollment.male AS enrrollment_male /*Masculino*/,
		enrrollment.url_photo AS enrrollment_url_photo /*Foto*/,
		enrrollment.comment AS enrrollment_comment /*Comentario*/,
		enrrollment.birth_country_code AS enrrollment_birth_country_code /*País Nacimiento - Código ISO 3166-1 Alfa-2*/,
		enrrollment.birth_admin_area_level1_code AS enrrollment_birth_admin_area_level1_code /*Provincia Nacimiento - Código ISO 3166-2*/,
		enrrollment.birth_admin_area_level2 AS enrrollment_birth_admin_area_level2 /*Departamento / Distrito Nacimiento*/,
		enrrollment.birth_locality AS enrrollment_birth_locality /*Localidad Nacimiento*/,
		enrrollment.birth_lat AS enrrollment_birth_lat /*Latitud Nacimiento*/,
		enrrollment.birth_lng AS enrrollment_birth_lng /*Longitud Nacimiento*/,
		enrrollment.institution_original_name AS enrrollment_institution_original_name /*Nombre en el idioma original*/,
		enrrollment.institution_web_site AS enrrollment_institution_web_site /*Sitio Web*/,
		enrrollment.institution_country_code AS enrrollment_institution_country_code /*País Nacionalidad - Código ISO 3166-1 Alfa-2*/,
		enrrollment.number_enrrollment AS enrrollment_number_enrrollment /*N°*/,
		enrrollment.check_out_date AS enrrollment_check_out_date /*Fecha Check Out*/
	FROM kuntur.unc_in_enrrollment
	JOIN kuntur.enrrollment
		ON kuntur.unc_in_enrrollment.id = kuntur.enrrollment.id